### PR TITLE
Wrap validations in try/except so we can emit some logging

### LINKED ISSUE #22: ValidationErrors should log the source json which failed to be parsed/validated
So we don't rely as much on full tracing/debug being enabled.

### PR DESCRIPTION
**Pull request by WebSpider**
Fixes #22

### CODE REVIEW

**Review by Prior99 — APPROVED** [review]

**Comment by WebSpider** [comment]
Conflicts with #31, let's see how we can catch validationerrors in mashu

**Comment by dvx76** [comment]
> Conflicts with #31, let's see how we can catch validationerrors in mashu

We may not need too sincee mashu spits out failures like in skodaconnect/homeassistant-myskoda#34

**Comment by Prior99** [comment]
In the meantime I had added this:

```python
    async def _make_get_request[T](self, url: str, deserialize: Callable[[str], T]) -> T:
        async with self.session.get(
            f"{BASE_URL_SKODA}/api{url}",
            headers=await self._headers(),
        ) as response:
            response_text = await response.text()
            try:
                data = deserialize(response_text)
            except Exception:
                _LOGGER.exception(
                    "Failed to load data from url %s. Return value was '%s'", url, response_text
                )
                raise
            else:
                return data
```

Which already wraps all get requests.

Is this PR still needed?

If yes, can we find a more generic way?

**Comment by dvx76** [comment]
I think we can close this. If we still need more/better logs it will bubble up again while looking at issues.

**Pull request closed without merging**
